name = "python"
language-servers = [ "pyright" ]

[language-server.pyright]
command = "pyright-langserver"

[language-server.pyright.config]
python.pythonPath = "/home/connor/.p/bin/python"



[[language]]
name = "c"
language-servers = [ "clangd" ]
